### ISSUE TITLE
Add travis for tests.

### ISSUE THREAD

**Issue by TheSavior** [cpojer/js-codemod#8]
I'm trying to get the tests to run locally before adding a PR and when I run `npm test` I get:

```
$ npm test

> js-codemod@7.0.0 test /Users/me/projects/js-codemod
> jest

Using Jest CLI v0.4.19
Waiting on 1 test...
MacBook-Pro:js-codemod$ 
```

It doesn't look like any tests are running. I was going to look at the travis setup to see how that was working but noticed that none of the tests are running.

Can you get travis set up so we can verify these transforms (and thus I can figure out how to run my test suite locally)?

**Comment by cpojer** [comment]
Uh, jest 0.4 only works with node 0.10, I forgot to update it. That might be the issue here if you are on node 4.

**Comment by TheSavior** [comment]
Ah, great. Dropping to 0.10 ran, but failed.

```
 FAIL  test/__tests__/transform-tests.js (2.934s)
arrow-function-arguments-test.js: arrow function uses "args" already. Please rename this identifier first.
WARNING: A variable binding in a `for` loop is accessed inside a new scope. This could be indicative of a race condition or other unintended access. We have left the binding as a `var`. View the following code at `no-vars-test.js#65`
for (var i = 0, z = 77; i < 10; i++) {
  setTimeout(() => console.log(i))
}

WARNING: A variable binding in a `for` loop is accessed inside a new scope. This could be indicative of a race condition or other unintended access. We have left the binding as a `var`. View the following code at `no-vars-test.js#69`
for (var j = 0; j < 10; j++) {
  _.defer(function () {
    console.log(j)
  });
}

● Transform Tests › it transforms the "use strict" tests correctly
  - TypeError: Cannot read property 'length' of undefined
        at module.exports (/Users/eli/projects/js-codemod/transforms/use-strict.js:28:12)
        at test (/Users/eli/projects/js-codemod/test/__tests__/transform-tests.js:28:11)
        at Spec.<anonymous> (/Users/eli/projects/js-codemod/test/__tests__/transform-tests.js:34:5)
        at jasmine.Block.execute (/Users/eli/projects/js-codemod/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:1065:17)
        at jasmine.Queue.next_ (/Users/eli/projects/js-codemod/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:2098:31)
        at null._onTimeout (/Users/eli/projects/js-codemod/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:2088:18)
        at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
● Transform Tests › it transforms the "touchable" tests correctly
  - TypeError: Cannot read property 'push' of undefined
        at NodePath.<anonymous> (/Users/eli/projects/js-codemod/transforms/touchable.js:35:45)
        at /Users/eli/projects/js-codemod/node_modules/jscodeshift/dist/Collection.js:90:25
        at Array.forEach (native)
        at Collection.forEach (/Users/eli/projects/js-codemod/node_modules/jscodeshift/dist/Collection.js:89:20)
        at module.exports (/Users/eli/projects/js-codemod/transforms/touchable.js:18:27)
        at test (/Users/eli/projects/js-codemod/test/__tests__/transform-tests.js:28:11)
        at Spec.<anonymous> (/Users/eli/projects/js-codemod/test/__tests__/transform-tests.js:64:5)
        at jasmine.Block.execute (/Users/eli/projects/js-codemod/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:1065:17)
        at jasmine.Queue.next_ (/Users/eli/projects/js-codemod/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:2098:31)
        at jasmine.Queue.start (/Users/eli/projects/js-codemod/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:2051:8)
        at Spec.jasmine.Spec.execute (/Users/eli/projects/js-codemod/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:2378:14)
        at jasmine.Queue.next_ (/Users/eli/projects/js-codemod/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:2098:31)
        at onComplete (/Users/eli/projects/js-codemod/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:2094:18)
        at Spec.jasmine.Spec.finish (/Users/eli/projects/js-codemod/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:2352:5)
        at null.onComplete (/Users/eli/projects/js-codemod/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:2379:10)
        at jasmine.Queue.next_ (/Users/eli/projects/js-codemod/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:2108:14)
        at null._onTimeout (/Users/eli/projects/js-codemod/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:2088:18)
        at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
1 test failed, 0 tests passed (1 total)
```

And based on the conversation at https://github.com/facebook/jscodeshift/issues/64, it would be valuable if https://github.com/reactjs/react-codemod/ had working CI as well.

**Comment by cpojer** [comment]
currently wrapping up a codemod. I'll fix testing in this repo afterwards.

**Comment by cpojer** [comment]
Alright, tests are all fixed up both here and on react-codemod, now both using the latest version of jest and node.
